#!/usr/bin/env python3
"""COVERAGE.md generator: llvm-cov export JSON on stdin, markdown on stdout.

Invoked by tools/coverage.sh. The output carries no timestamp, so the file
only changes when the numbers do.
"""

import json
import os
import sys

BAR_WIDTH = 20


def bar(percent: float) -> str:
    # A full bar means exactly 100% — anything less keeps a visible gap.
    filled = round(percent / 100 * BAR_WIDTH)
    if percent < 100 and filled == BAR_WIDTH:
        filled = BAR_WIDTH - 1
    return "`" + "█" * filled + "░" * (BAR_WIDTH - filled) + "`"


def pct(summary: dict, key: str) -> str:
    s = summary[key]
    if s["count"] == 0:
        return "—"
    return f"{s['percent']:.2f}%"


def main() -> None:
    export = json.load(sys.stdin)
    data = export["data"][0]
    files = sorted(
        data["files"],
        key=lambda f: (-f["summary"]["lines"]["percent"], f["filename"]),
    )
    totals = data["totals"]

    out = sys.stdout
    out.write("# Coverage\n\n")
    out.write("<!-- Generated by tools/coverage.sh — do not edit. -->\n\n")
    out.write(
        "Line coverage of the C++ core (`words_core`) under the host test\n"
        "suite (colocated unit tests + approvals), measured with clang\n"
        "source-based coverage. Regenerate with `tools/coverage.sh`; add\n"
        "`--html` for a line-by-line drilldown.\n\n"
    )

    lines = totals["lines"]
    out.write("| Metric | Coverage | Covered / total |\n")
    out.write("|---|---|---|\n")
    out.write(
        f"| **Lines** | **{lines['percent']:.2f}%** "
        f"| {lines['covered']:,} / {lines['count']:,} |\n"
    )
    for label, key in (
        ("Functions", "functions"),
        ("Regions", "regions"),
        ("Branches", "branches"),
    ):
        s = totals[key]
        out.write(
            f"| {label} | {s['percent']:.2f}% "
            f"| {s['covered']:,} / {s['count']:,} |\n"
        )
    out.write("\n")

    out.write("| File | Line coverage | | Missed lines | Functions | Branches |\n")
    out.write("|---|---|---|---|---|---|\n")
    for f in files:
        s = f["summary"]
        name = os.path.basename(f["filename"])
        missed = s["lines"]["count"] - s["lines"]["covered"]
        out.write(
            f"| {name} | {bar(s['lines']['percent'])} "
            f"| {pct(s, 'lines')} | {missed} "
            f"| {pct(s, 'functions')} | {pct(s, 'branches')} |\n"
        )


if __name__ == "__main__":
    main()
